plugins {
  id "com.github.node-gradle.node" version "7.1.0"
}

apply plugin:'java'

node {
  version = '10.16.3'
  npmVersion = '6.9.0'
  distBaseUrl = "https://direct.nodejs.org/dist"
  download = true
  workDir = file("${project.projectDir}/node")
//  nodeModulesDir = file("${project.projectDir}/")
}

tasks.register('npmClean', Delete) {
  final def webDir = "${rootDir}/frontend"
  delete "${webDir}/node"
  delete "${webDir}/node_modules"
  delete "${webDir}/dist"
  delete "${webDir}/coverage"
}

// clean task for npm
clean.dependsOn(npmClean)

// build task for npm
//processResources.dependsOn(npm_install)
processResources.dependsOn(npm_run_build)

jar {
  archiveBaseName = 'alfio-pi-frontend'
  version = "${project.version}"
  into("META-INF/resources/webjars/${archiveBaseName}/${project.version}") {
      from 'dist'
  }
}

// run all task
tasks.register('runAll') {}
runAll.dependsOn(npm_run_start)
