name: build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/cache@v1
              with:
                  path: ~/.gradle/caches
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-
            - uses: actions/cache@v1
              with:
                  path: ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradlew') }}
                  restore-keys: |
                      ${{ runner.os }}-gradlew-
            - name: Set up JDK 17
              uses: actions/setup-java@v1
              with:
                  java-version: 17
            - name: Build with Gradle
              run: ./gradlew packageDeb
            -   name: 'Upload Build'
                uses: actions/upload-artifact@v2
                with:
                    name: dist
                    path: build
                    retention-days: 5